// src/models/Observation.js

const { DataTypes, Model } = require('sequelize');
const { sequelize } = require('../config/database');

class Observation extends Model {}

Observation.init(
  {
    // --- Core Fields ---
    id: {
      type: DataTypes.INTEGER, // Must be TEXT for auto-increment (SERIAL in PostgreSQL)
      autoIncrement: true,
      primaryKey: true,
    },
    timestamp: {
      type: DataTypes.DATE,
      allowNull: false,
      defaultValue: DataTypes.NOW,
    },
    value: {
      type: DataTypes.TEXT,
      allowNull: true,
    },
    location: {
      type: DataTypes.TEXT,
      allowNull: true,
    },
    type: {
      type: DataTypes.TEXT,
      allowNull: true,
    },
    
    // --- NEW SURVEY FIELDS ---
    SubmissionDate: { type: DataTypes.DATE },
    starttime: { type: DataTypes.DATE },
    endtime: { type: DataTypes.DATE },
    deviceid: { type: DataTypes.TEXT },
    devicephonenum: { type: DataTypes.TEXT },
    username: { type: DataTypes.TEXT },
    device_info: { type: DataTypes.TEXT },
    
    // Changed back to TEXT/TEXT for mathematical fields, assuming you'll clean 'N/A' data
    duration: { type: DataTypes.TEXT }, 
    geo1: { type: DataTypes.TEXT },
    Visit_photo: { type: DataTypes.TEXT },
    State: { type: DataTypes.TEXT },
    District: { type: DataTypes.TEXT },
    udise_Code: { type: DataTypes.TEXT },
    Block: { type: DataTypes.TEXT },
    Cluster: { type: DataTypes.TEXT },
    School: { type: DataTypes.TEXT },
    Confirmation_Details: { type: DataTypes.TEXT },
    designation: { type: DataTypes.TEXT },
    staff_name: { type: DataTypes.TEXT },
    cal_startdate: { type: DataTypes.DATE },
    visit_date: { type: DataTypes.DATE },
    cal_visitdate: { type: DataTypes.DATE },
    date_diff: { type: DataTypes.TEXT }, // Assuming this should be a number (days difference)
    school_type: { type: DataTypes.TEXT },
    Visit_type: { type: DataTypes.TEXT },
    Class: { type: DataTypes.TEXT },
    Subject: { type: DataTypes.TEXT },
    teacher_name: { type: DataTypes.TEXT },
    Teacher_Gender: { type: DataTypes.TEXT },
    Teacher_Designation: { type: DataTypes.TEXT },
    
    // Count fields changed back to TEXT
    enrolled_students: { type: DataTypes.TEXT }, 
    enrolled_students_boys: { type: DataTypes.TEXT }, 
    enrolled_students_girls: { type: DataTypes.TEXT }, 
    Present_students: { type: DataTypes.TEXT }, 
    Present_students_boys: { type: DataTypes.TEXT }, 
    Present_students_girls: { type: DataTypes.TEXT }, 
    
    // Keep as TEXT for question/checkbox fields
    Q3: { type: DataTypes.TEXT },
    Q3_A: { type: DataTypes.TEXT },
    Lessonplan_week: { type: DataTypes.TEXT },
    Lessonplan_day: { type: DataTypes.TEXT },
    Period: { type: DataTypes.TEXT },
    class_situation: { type: DataTypes.TEXT },
    mg_situation: { type: DataTypes.TEXT },
    Q3_4_1: { type: DataTypes.TEXT },
    Q3_4_2: { type: DataTypes.TEXT },
    Q3_4_3: { type: DataTypes.TEXT },
    Q3_5_1: { type: DataTypes.TEXT },
    Q3_5_2: { type: DataTypes.TEXT },
    Q3_5_3: { type: DataTypes.TEXT },
    Q3_5_4: { type: DataTypes.TEXT },
    Q3_5_5: { type: DataTypes.TEXT },
    Q3_H_1: { type: DataTypes.TEXT },
    Q3_H_2: { type: DataTypes.TEXT },
    Q3_H_3: { type: DataTypes.TEXT },
    Q3_H_4: { type: DataTypes.TEXT },
    Q3_H_5: { type: DataTypes.TEXT },
    Q3_H_6: { type: DataTypes.TEXT },
    Q3_H_7: { type: DataTypes.TEXT },
    Q3_H_8: { type: DataTypes.TEXT },
    Q3_H_9: { type: DataTypes.TEXT },
    Q3_H_10: { type: DataTypes.TEXT },
    Q3_H_11: { type: DataTypes.TEXT },
    Q4_4: { type: DataTypes.TEXT },
    Q4_5: { type: DataTypes.TEXT },
    Q4_6: { type: DataTypes.TEXT },
    Q4_7: { type: DataTypes.TEXT },
    Q4_8: { type: DataTypes.TEXT },
    Q5_A1: { type: DataTypes.TEXT },
    Q5_A2: { type: DataTypes.TEXT },
    Q5_A2_A: { type: DataTypes.TEXT },
    Q5_A2_B: { type: DataTypes.TEXT },
    Q5_A3: { type: DataTypes.TEXT },
    Q5_A3_A: { type: DataTypes.TEXT },
    Q5_A3_B: { type: DataTypes.TEXT },
    Q5_A4_A: { type: DataTypes.TEXT },
    Q5_A4_B: { type: DataTypes.TEXT },
    Q5_B1: { type: DataTypes.TEXT },
    Q5_B2: { type: DataTypes.TEXT },
    Q5_B3: { type: DataTypes.TEXT },
    Q5_B4: { type: DataTypes.TEXT },
    Q5_B5: { type: DataTypes.TEXT },
    Q5_B6: { type: DataTypes.TEXT },
    Q5_B7_A: { type: DataTypes.TEXT },
    Q5_B7_B: { type: DataTypes.TEXT },
    Q6_1: { type: DataTypes.TEXT },
    Q7_1: { type: DataTypes.TEXT },
    Q7_1A: { type: DataTypes.TEXT },
    Q7_1B: { type: DataTypes.TEXT },
    
    // SSI fields changed back to TEXT/TEXT for calculations
    ssi_lit_1: { type: DataTypes.TEXT }, 
    ssi_lit_2: { type: DataTypes.TEXT },
    ssi_lit_3: { type: DataTypes.TEXT },
    ssi_lit_4: { type: DataTypes.TEXT },
    ssi_lit_pp_final: { type: DataTypes.TEXT },
    ssi_num_1: { type: DataTypes.TEXT },
    ssi_num_2: { type: DataTypes.TEXT },
    ssi_num_3: { type: DataTypes.TEXT },
    ssi_num_4: { type: DataTypes.TEXT },
    ssi_num_pp_final: { type: DataTypes.TEXT },
    ssi_gp_final: { type: DataTypes.TEXT },
    ssi_all_final: { type: DataTypes.TEXT },
    ssi_3_effectiveness: { type: DataTypes.TEXT },
    ssi_2_effectiveness: { type: DataTypes.TEXT },
    
    AY: { type: DataTypes.TEXT },
    visit_month_year: { type: DataTypes.TEXT },
    instanceID: { type: DataTypes.TEXT },
    formdef_version: { type: DataTypes.TEXT },
    formdef_id: { type: DataTypes.TEXT },
    KEY: { type: DataTypes.TEXT },
    Mentor_type: { type: DataTypes.TEXT },
    CAC_Name: { type: DataTypes.TEXT },
    CAC_Gender: { type: DataTypes.TEXT },
    CAC_Mobile_Number: { type: DataTypes.TEXT },
    teacher_mobile: { type: DataTypes.TEXT },
    
    // Remaining Q fields kept as TEXT
    Q3_M_1: { type: DataTypes.TEXT },
    Q3_8_1: { type: DataTypes.TEXT },
    Q3_8_2: { type: DataTypes.TEXT },
    Q3_8_3: { type: DataTypes.TEXT },
    Q3_8_4: { type: DataTypes.TEXT },
    Q3_8_5: { type: DataTypes.TEXT },
    Q3_8_6: { type: DataTypes.TEXT },
    Q3_8_8: { type: DataTypes.TEXT },
    Q3_8_7: { type: DataTypes.TEXT },
    Q3_8_9: { type: DataTypes.TEXT },
    Q3_M_2: { type: DataTypes.TEXT },
    Q3_M_3: { type: DataTypes.TEXT },
    Q3_M_3A: { type: DataTypes.TEXT },
    Q3_M_4: { type: DataTypes.TEXT },
    Q3_M_5: { type: DataTypes.TEXT },
    Q3_M_6: { type: DataTypes.TEXT },
    Q8_1: { type: DataTypes.TEXT },
    Q8_2: { type: DataTypes.TEXT },
    Q8_3: { type: DataTypes.TEXT },
    Q8_4: { type: DataTypes.TEXT },
    Q8_5: { type: DataTypes.TEXT },
    Q8_6: { type: DataTypes.TEXT },
    Q8_7: { type: DataTypes.TEXT },
    Q8_8: { type: DataTypes.TEXT },
    Q8_9: { type: DataTypes.TEXT },
    Q8_10: { type: DataTypes.TEXT },
    Q8_11: { type: DataTypes.TEXT },
    Q8_12: { type: DataTypes.TEXT },
    Q8_13: { type: DataTypes.TEXT },
    Q8_14: { type: DataTypes.TEXT },
    Q8_14A: { type: DataTypes.TEXT },
    Q8_14B: { type: DataTypes.TEXT },
    Q8_16: { type: DataTypes.TEXT },
    Q8_17: { type: DataTypes.TEXT },
    Q8_18: { type: DataTypes.TEXT },
    Q8_19: { type: DataTypes.TEXT },
    Q8_20: { type: DataTypes.TEXT },
    Q8_21: { type: DataTypes.TEXT },
    Q8_22: { type: DataTypes.TEXT },
    other_remark: { type: DataTypes.TEXT },
    Q6_1A: { type: DataTypes.TEXT },
    Q6_1_1: { type: DataTypes.TEXT },
    Q6_1_2: { type: DataTypes.TEXT },
    Q6_1_3: { type: DataTypes.TEXT },
    Q6_1_4: { type: DataTypes.TEXT },
    Q8_15: { type: DataTypes.TEXT },
    Q3_6_1: { type: DataTypes.TEXT },
    Q6_1_2_1: { type: DataTypes.TEXT },
    Q6_1_5: { type: DataTypes.TEXT },
    Q3_H_12: { type: DataTypes.TEXT },
    Q3_M_1_oth: { type: DataTypes.TEXT },
    Q3_B: { type: DataTypes.TEXT },
    Q3_M_7: { type: DataTypes.TEXT },
    Q8_3fb: { type: DataTypes.TEXT },
    Blocks_Num: { type: DataTypes.TEXT }, // Changed back to TEXT
    Q3_H_3_NA: { type: DataTypes.TEXT },
    Q3_H_1_NA: { type: DataTypes.TEXT },
    Q3_H_2_NA: { type: DataTypes.TEXT },
    Q3_8_3_NA: { type: DataTypes.TEXT },
    Q3_H_5_NA: { type: DataTypes.TEXT },
    Q3_H_4_NA: { type: DataTypes.TEXT },
    wb_avail: { type: DataTypes.TEXT },
    tlm_avail: { type: DataTypes.TEXT },
    Q4_9: { type: DataTypes.TEXT },
    Q4_5_NA: { type: DataTypes.TEXT },
    Q3_H_6_NA: { type: DataTypes.TEXT },
    Q3_8_2_NA: { type: DataTypes.TEXT },
    Q3_8_8_NA: { type: DataTypes.TEXT },
    Q3_8_5_NA: { type: DataTypes.TEXT },
    Q3_8_7_NA: { type: DataTypes.TEXT },
    Q3_8_6_NA: { type: DataTypes.TEXT },
    Q3_8_1_NA: { type: DataTypes.TEXT },
    Q3_8_9_NA: { type: DataTypes.TEXT },
  },
  {
    tableName: 'observations',
    sequelize, 
  }
);

module.exports = { Observation };